package com.redhat.empowered.businessservice;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.4.redhat-621090
 * 2016-09-26T00:40:43.846+03:00
 * Generated source version: 3.0.4.redhat-621090
 * 
 */
@WebServiceClient(name = "personSoapHttpService", 
                  wsdlLocation = "classpath:wsdl/businessService.wsdl",
                  targetNamespace = "http://www.redhat.com/empowered/businessService") 
public class PersonSoapHttpService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.redhat.com/empowered/businessService", "personSoapHttpService");
    public final static QName PersonSoapHttpPort = new QName("http://www.redhat.com/empowered/businessService", "personSoapHttpPort");
    static {
        URL url = PersonSoapHttpService.class.getClassLoader().getResource("wsdl/businessService.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(PersonSoapHttpService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/businessService.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    public PersonSoapHttpService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PersonSoapHttpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PersonSoapHttpService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PersonSoapHttpService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PersonSoapHttpService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PersonSoapHttpService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns PersonPortType
     */
    @WebEndpoint(name = "personSoapHttpPort")
    public PersonPortType getPersonSoapHttpPort() {
        return super.getPort(PersonSoapHttpPort, PersonPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PersonPortType
     */
    @WebEndpoint(name = "personSoapHttpPort")
    public PersonPortType getPersonSoapHttpPort(WebServiceFeature... features) {
        return super.getPort(PersonSoapHttpPort, PersonPortType.class, features);
    }

}
